from classes.game import *
from classes.menu import *
from tud_test_base import set_keyboard_input, get_display_output
from io import StringIO 
from unittest.mock import Mock, patch
from unittest import mock
import sys
import pytest
import os
import random
import math
import statistics
import classes

pytestmark = pytest.mark.skipif("generate_remaining_building_string" not in dir(classes.game.Game), reason="view remaining buildings on side not implemented")

defaultBuildingPool = {"HSE":8, "FAC":8, "SHP": 8, "HWY":8, "BCH":8}
newBuildingPool = {"HSE":8, "FAC":8, "SHP": 8, "PRK":8, "MON":8}
newBuildingPool1PRK = {"HSE":8, "FAC":8, "SHP": 8, "PRK":7, "MON":8}
newBuildingPool2PRK = {"HSE":8, "FAC":8, "SHP": 8, "PRK":6, "MON":8}
newBuildingPool3PRK = {"HSE":8, "FAC":8, "SHP": 8, "PRK":5, "MON":8}
newBuildingPool4PRK = {"HSE":8, "FAC":8, "SHP": 8, "PRK":4, "MON":8}
newBuildingPool5PRK = {"HSE":8, "FAC":8, "SHP": 8, "PRK":3, "MON":8}
newBuildingPool6PRK = {"HSE":8, "FAC":8, "SHP": 8, "PRK":2, "MON":8}
newBuildingPool7PRK = {"HSE":8, "FAC":8, "SHP": 8, "PRK":1, "MON":8}
newBuildingPool8PRK = {"HSE":8, "FAC":8, "SHP": 8, "PRK":0, "MON":8}
newBuildingPool1MON = {"HSE":8, "FAC":8, "SHP": 8, "PRK":8, "MON":7}
newBuildingPool4MON = {"HSE":8, "FAC":8, "SHP": 8, "PRK":8, "MON":4}


gamemenuoptions = "1. Build a BCH\n2. Build a HSE\n3. See remaining buildings\n4. See current score\n\n5. Save game\n0. Exit to main menu"

gameMenu = ['1. Build a HSE',
            '2. Build a MON', 
            '3. See remaining buildings',
            '4. See current score',
            '', 
            '5. Save game', 
            '0. Exit to main menu', 
            'Your choice? ']

gameBoardDefault = [
        "     A     B     C     D           Building   Remaining",
        "  +-----+-----+-----+-----+        --------------------",
        " 1|     |     |     |     |        HSE      | 8",
        "  +-----+-----+-----+-----+        FAC      | 8",
        " 2|     |     |     |     |        SHP      | 8",
        "  +-----+-----+-----+-----+        HWY      | 8",
        " 3|     |     |     |     |        BCH      | 8",
        "  +-----+-----+-----+-----+",
        " 4|     |     |     |     |",
        "  +-----+-----+-----+-----+"]

gameBoard1PRK = [
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| PRK |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        PRK      | 7",
    " 3|     |     |     |     |        MON      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
]

gameBoard2PRK = [
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| PRK | PRK |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        PRK      | 6",
    " 3|     |     |     |     |        MON      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
]

gameBoard3PRK = [
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| PRK | PRK | PRK |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        PRK      | 5",
    " 3|     |     |     |     |        MON      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
]

gameBoard4PRK = [
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| PRK | PRK | PRK | PRK |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        PRK      | 4",
    " 3|     |     |     |     |        MON      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
]

gameBoard5PRK = [
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| PRK | PRK | PRK | PRK |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| PRK |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        PRK      | 3",
    " 3|     |     |     |     |        MON      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
]

gameBoard6PRK = [
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| PRK | PRK | PRK | PRK |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| PRK |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        PRK      | 2",
    " 3| PRK |     |     |     |        MON      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
]

gameBoard7PRK = [
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| PRK | PRK | PRK | PRK |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| PRK |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        PRK      | 1",
    " 3| PRK |     |     |     |        MON      | 8",
    "  +-----+-----+-----+-----+",
    " 4| PRK |     |     |     |",
    "  +-----+-----+-----+-----+",
]

gameBoard8PRK = [
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| PRK | PRK | PRK | PRK |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| PRK | PRK |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        PRK      | 0",
    " 3| PRK |     |     |     |        MON      | 8",
    "  +-----+-----+-----+-----+",
    " 4| PRK |     |     |     |",
    "  +-----+-----+-----+-----+"
]

gameBoard1MONCornerSquare = [
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| MON |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        PRK      | 8",
    " 3|     |     |     |     |        MON      | 7",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
]

gameBoard1MONNotCornerSquare = [
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     | MON |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        PRK      | 8",
    " 3|     |     |     |     |        MON      | 7",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
]

gameBoard3MONCorner1MONNotCorner = [
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| MON |     |     | MON |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     | MON |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        PRK      | 8",
    " 3|     |     |     |     |        MON      | 4",
    "  +-----+-----+-----+-----+",
    " 4| MON |     |     |     |",
    "  +-----+-----+-----+-----+",
]

gameBoard4MONCorner = [
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| MON |     |     | MON |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        PRK      | 8",
    " 3|     |     |     |     |        MON      | 4",
    "  +-----+-----+-----+-----+",
    " 4| MON |     |     | MON |",
    "  +-----+-----+-----+-----+",
]


actualBoard1PRK = [
[Park(0, 0), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()]]

actualBoard2PRK = [
[Park(0, 0), Park(1,0), Building(), Building()],
[Building(), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()]]

actualBoard3PRK = [
[Park(0, 0), Park(1,0), Park(2,0), Building()],
[Building(), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()]]

actualBoard4PRK = [
[Park(0, 0), Park(1,0), Park(2,0), Park(3,0)],
[Building(), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()]]

actualBoard5PRK = [
[Park(0, 0), Park(1,0), Park(2,0), Park(3,0)],
[Park(0, 1), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()]]

actualBoard6PRK = [
[Park(0, 0), Park(1,0), Park(2,0), Park(3,0)],
[Park(0, 1), Building(), Building(), Building()],
[Park(0, 2), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()]]

actualBoard7PRK = [
[Park(0, 0), Park(1,0), Park(2,0), Park(3,0)],
[Park(0, 1), Building(), Building(), Building()],
[Park(0, 2), Building(), Building(), Building()],
[Park(0, 3), Building(), Building(), Building()]]

actualBoard8PRK = [
[Park(0, 0), Park(1,0), Park(2,0), Park(3,0)],
[Park(0, 1), Park(1,1), Building(), Building()],
[Park(0, 2), Building(), Building(), Building()],
[Park(0, 3), Building(), Building(), Building()]]

actualBoard1MONCorner = [
[Monument(0, 0), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()]]

actualBoard1MONNotCorner = [
[Building(), Building(), Building(), Building()],
[Building(), Monument(1,1), Building(), Building()],
[Building(), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()]]

actualBoard3MONCorner1NotCorner = [
[Monument(0,0), Building(), Building(), Monument(3,0)],
[Building(), Monument(1,1), Building(), Building()],
[Building(), Building(), Building(), Building()],
[Monument(0,3), Building(), Building(), Building()]]

actualBoard4MONCorner = [
[Monument(0,0), Building(), Building(), Monument(3,0)],
[Building(), Building(), Building(), Building()],
[Building(), Building(), Building(), Building()],
[Monument(0,3), Building(), Building(), Monument(3,3)]]



score1PRK = [
"HSE: 0",
"FAC: 0",
"SHP: 0",
"PRK: 1 = 1",
"MON: 0",
"Total score: 1"]

score2PRK = [
"HSE: 0",
"FAC: 0",
"SHP: 0",
"PRK: 1 + 2 = 3",
"MON: 0",
"Total score: 3"]

score3PRK = [
"HSE: 0",
"FAC: 0",
"SHP: 0",
"PRK: 1 + 2 + 5 = 8",
"MON: 0",
"Total score: 8"]

score4PRK = [
"HSE: 0",
"FAC: 0",
"SHP: 0",
"PRK: 1 + 2 + 5 + 8 = 16",
"MON: 0",
"Total score: 16"]

score5PRK = [
"HSE: 0",
"FAC: 0",
"SHP: 0",
"PRK: 1 + 2 + 5 + 8 + 6 = 22",
"MON: 0",
"Total score: 22"]

score6PRK = [
"HSE: 0",
"FAC: 0",
"SHP: 0",
"PRK: 1 + 2 + 5 + 8 + 6 + 1 = 23",
"MON: 0",
"Total score: 23"]

score7PRK = [
"HSE: 0",
"FAC: 0",
"SHP: 0",
"PRK: 1 + 2 + 5 + 8 + 6 + 1 + 1 = 24",
"MON: 0",
"Total score: 24"]

score8PRK = [
"HSE: 0",
"FAC: 0",
"SHP: 0",
"PRK: 1 + 2 + 5 + 8 + 6 + 1 + 1 + 1 = 25",
"MON: 0",
"Total score: 25"]

score1MONCorner = [
"HSE: 0",
"FAC: 0",
"SHP: 0",
"PRK: 0",
"MON: 2 = 2",
"Total score: 2"]

score1MONNotCorner = [
"HSE: 0",
"FAC: 0",
"SHP: 0",
"PRK: 0",
"MON: 1 = 1",
"Total score: 1"]

score3MONCorner = [
"HSE: 0",
"FAC: 0",
"SHP: 0",
"PRK: 0",
"MON: 4 + 4 + 4 + 4 = 16",
"Total score: 16"]



def test_view_current_score_empty():
    """
    Test script to test viewing current score when there are 0 buildings on the board. (TC-07A)
    """
    set_keyboard_input(["4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["BCH", "HSE"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()
    
    assert result == ["", "Turn 1"] + gameBoardDefault + [
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 0",
    "FAC: 0",
    "SHP: 0",
    "HWY: 0",
    "BCH: 0",
    "Total score: 0",
    "",
    "Turn 1"] + gameBoardDefault + [
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']


def test_view_current_score_bch_center_of_city():
    """
    Test script to test viewing current score when a single "BCH" is on the board not on the right or left side of the city. (TC-07B)
    """
    set_keyboard_input(["1","b2","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["BCH", "HSE"], "2": ["BCH", "HSE"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1"] + gameBoardDefault + [
        '1. Build a BCH',
        '2. Build a HSE', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ',
        "Build where? ",
        "",
        "Turn 2",
        "     A     B     C     D           Building   Remaining",
        "  +-----+-----+-----+-----+        --------------------",
        " 1|     |     |     |     |        HSE      | 8",
        "  +-----+-----+-----+-----+        FAC      | 8",
        " 2|     | BCH |     |     |        SHP      | 8",
        "  +-----+-----+-----+-----+        HWY      | 8",
        " 3|     |     |     |     |        BCH      | 7",
        "  +-----+-----+-----+-----+",
        " 4|     |     |     |     |",
        "  +-----+-----+-----+-----+",
        '1. Build a BCH',
        '2. Build a HSE', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ',
        "",
        "HSE: 0",
        "FAC: 0",
        "SHP: 0",
        "HWY: 0",
        "BCH: 1 = 1",
        "Total score: 1",
        "",
        "Turn 2",
        "     A     B     C     D           Building   Remaining",
        "  +-----+-----+-----+-----+        --------------------",
        " 1|     |     |     |     |        HSE      | 8",
        "  +-----+-----+-----+-----+        FAC      | 8",
        " 2|     | BCH |     |     |        SHP      | 8",
        "  +-----+-----+-----+-----+        HWY      | 8",
        " 3|     |     |     |     |        BCH      | 7",
        "  +-----+-----+-----+-----+",
        " 4|     |     |     |     |",
        "  +-----+-----+-----+-----+",
        '1. Build a BCH',
        '2. Build a HSE', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ']

def test_view_current_score_bch_right_or_left_of_city():
    """
    Test script to test viewing current score when a single "BCH" is on the board on the right or left side of the city. (TC-07B)
    """
    set_keyboard_input(["1","a1","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["BCH", "HSE"], "2": ["BCH", "HSE"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1"] + gameBoardDefault + [
        '1. Build a BCH',
        '2. Build a HSE', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ',
        "Build where? ",
        "",
        "Turn 2",
        "     A     B     C     D           Building   Remaining",
        "  +-----+-----+-----+-----+        --------------------",
        " 1| BCH |     |     |     |        HSE      | 8",
        "  +-----+-----+-----+-----+        FAC      | 8",
        " 2|     |     |     |     |        SHP      | 8",
        "  +-----+-----+-----+-----+        HWY      | 8",
        " 3|     |     |     |     |        BCH      | 7",
        "  +-----+-----+-----+-----+",
        " 4|     |     |     |     |",
        "  +-----+-----+-----+-----+",
        '1. Build a BCH',
        '2. Build a HSE', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ',
        "",
        "HSE: 0",
        "FAC: 0",
        "SHP: 0",
        "HWY: 0",
        "BCH: 3 = 3",
        "Total score: 3",
        "",
        "Turn 2",
        "     A     B     C     D           Building   Remaining",
        "  +-----+-----+-----+-----+        --------------------",
        " 1| BCH |     |     |     |        HSE      | 8",
        "  +-----+-----+-----+-----+        FAC      | 8",
        " 2|     |     |     |     |        SHP      | 8",
        "  +-----+-----+-----+-----+        HWY      | 8",
        " 3|     |     |     |     |        BCH      | 7",
        "  +-----+-----+-----+-----+",
        " 4|     |     |     |     |",
        "  +-----+-----+-----+-----+",
        '1. Build a BCH',
        '2. Build a HSE', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ']

def test_view_current_score_fac_single_fac():
    """
    Test script to test viewing current score when a single "FAC" is on the board. (TC-07C)
    """
    set_keyboard_input(["1","a1","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["FAC", "HWY"], "2": ["FAC", "HWY"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1"] + gameBoardDefault + [
        '1. Build a FAC',
        '2. Build a HWY', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ',
        "Build where? ",
        "",
        "Turn 2",
        "     A     B     C     D           Building   Remaining",
        "  +-----+-----+-----+-----+        --------------------",
        " 1| FAC |     |     |     |        HSE      | 8",
        "  +-----+-----+-----+-----+        FAC      | 7",
        " 2|     |     |     |     |        SHP      | 8",
        "  +-----+-----+-----+-----+        HWY      | 8",
        " 3|     |     |     |     |        BCH      | 8",
        "  +-----+-----+-----+-----+",
        " 4|     |     |     |     |",
        "  +-----+-----+-----+-----+",
        '1. Build a FAC',
        '2. Build a HWY', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ',
        "",
        "HSE: 0",
        "FAC: 1 = 1",
        "SHP: 0",
        "HWY: 0",
        "BCH: 0",
        "Total score: 1",
        "",
        "Turn 2",
        "     A     B     C     D           Building   Remaining",
        "  +-----+-----+-----+-----+        --------------------",
        " 1| FAC |     |     |     |        HSE      | 8",
        "  +-----+-----+-----+-----+        FAC      | 7",
        " 2|     |     |     |     |        SHP      | 8",
        "  +-----+-----+-----+-----+        HWY      | 8",
        " 3|     |     |     |     |        BCH      | 8",
        "  +-----+-----+-----+-----+",
        " 4|     |     |     |     |",
        "  +-----+-----+-----+-----+",
        '1. Build a FAC',
        '2. Build a HWY', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ']
    
def test_view_current_score_fac_4fac():
    """
    Test script to test viewing current score when a 4 "FAC" is on the board. (TC-07C)
    """
    set_keyboard_input(["1","a1","1","b1","1","c1","1","d1","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["FAC", "HWY"], "2": ["FAC", "HWY"], "3": ["FAC", "HWY"], "4": ["FAC", "HWY"], "5": ["FAC", "HWY"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1"] + gameBoardDefault + [
        '1. Build a FAC',
        '2. Build a HWY', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ',
        "Build where? ",
        "",
        "Turn 2",
        "     A     B     C     D           Building   Remaining",
        "  +-----+-----+-----+-----+        --------------------",
        " 1| FAC |     |     |     |        HSE      | 8",
        "  +-----+-----+-----+-----+        FAC      | 7",
        " 2|     |     |     |     |        SHP      | 8",
        "  +-----+-----+-----+-----+        HWY      | 8",
        " 3|     |     |     |     |        BCH      | 8",
        "  +-----+-----+-----+-----+",
        " 4|     |     |     |     |",
        "  +-----+-----+-----+-----+",
        '1. Build a FAC',
        '2. Build a HWY', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ',
        "Build where? ",
        "",
        "Turn 3",
        "     A     B     C     D           Building   Remaining",
        "  +-----+-----+-----+-----+        --------------------",
        " 1| FAC | FAC |     |     |        HSE      | 8",
        "  +-----+-----+-----+-----+        FAC      | 6",
        " 2|     |     |     |     |        SHP      | 8",
        "  +-----+-----+-----+-----+        HWY      | 8",
        " 3|     |     |     |     |        BCH      | 8",
        "  +-----+-----+-----+-----+",
        " 4|     |     |     |     |",
        "  +-----+-----+-----+-----+",
        '1. Build a FAC',
        '2. Build a HWY', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ',
        "Build where? ",
        "",
        "Turn 4",
        "     A     B     C     D           Building   Remaining",
        "  +-----+-----+-----+-----+        --------------------",
        " 1| FAC | FAC | FAC |     |        HSE      | 8",
        "  +-----+-----+-----+-----+        FAC      | 5",
        " 2|     |     |     |     |        SHP      | 8",
        "  +-----+-----+-----+-----+        HWY      | 8",
        " 3|     |     |     |     |        BCH      | 8",
        "  +-----+-----+-----+-----+",
        " 4|     |     |     |     |",
        "  +-----+-----+-----+-----+",
        '1. Build a FAC',
        '2. Build a HWY', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ',
        "Build where? ",
        "",
        "Turn 5",
        "     A     B     C     D           Building   Remaining",
        "  +-----+-----+-----+-----+        --------------------",
        " 1| FAC | FAC | FAC | FAC |        HSE      | 8",
        "  +-----+-----+-----+-----+        FAC      | 4",
        " 2|     |     |     |     |        SHP      | 8",
        "  +-----+-----+-----+-----+        HWY      | 8",
        " 3|     |     |     |     |        BCH      | 8",
        "  +-----+-----+-----+-----+",
        " 4|     |     |     |     |",
        "  +-----+-----+-----+-----+",
        '1. Build a FAC',
        '2. Build a HWY', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ',
        "",
        "HSE: 0",
        "FAC: 4 + 4 + 4 + 4 = 16",
        "SHP: 0",
        "HWY: 0",
        "BCH: 0",
        "Total score: 16",
        "",
        "Turn 5",
        "     A     B     C     D           Building   Remaining",
        "  +-----+-----+-----+-----+        --------------------",
        " 1| FAC | FAC | FAC | FAC |        HSE      | 8",
        "  +-----+-----+-----+-----+        FAC      | 4",
        " 2|     |     |     |     |        SHP      | 8",
        "  +-----+-----+-----+-----+        HWY      | 8",
        " 3|     |     |     |     |        BCH      | 8",
        "  +-----+-----+-----+-----+",
        " 4|     |     |     |     |",
        "  +-----+-----+-----+-----+",
        '1. Build a FAC',
        '2. Build a HWY', 
        '3. See remaining buildings',
        '4. See current score',
        '', 
        '5. Save game', 
        '0. Exit to main menu', 
        'Your choice? ']

def test_view_current_score_fac_5fac():
    """
    Test script to test viewing current score when a 5 "FAC" is on the board. (TC-07C)
    """
    set_keyboard_input(["1","a1","1","b1","1","c1","1","d1","1","a2","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["FAC", "HWY"], "2": ["FAC", "HWY"], "3": ["FAC", "HWY"], "4": ["FAC", "HWY"], "5": ["FAC", "HWY"], "6": ["FAC", "HWY"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()
    
    assert result == ["", "Turn 1",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| FAC |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 7",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| FAC | FAC |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 6",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 4",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| FAC | FAC | FAC |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 5",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 5",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| FAC | FAC | FAC | FAC |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 4",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 6",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| FAC | FAC | FAC | FAC |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 3",
    " 2| FAC |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 0",
    "FAC: 4 + 4 + 4 + 4 + 1 = 17",
    "SHP: 0",
    "HWY: 0",
    "BCH: 0",
    "Total score: 17",
    "",
    "Turn 6",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| FAC | FAC | FAC | FAC |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 3",
    " 2| FAC |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']




def test_view_current_score_hse_single_hse():
    """
    Test script to test viewing current score when a single "HSE" is on the board. (TC-07D)
    """
    set_keyboard_input(["2","a1","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["BCH", "HSE"], "2": ["BCH", "HSE"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    
    assert result == ["", "Turn 1",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| HSE |     |     |     |        HSE      | 7",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 0",
    "FAC: 0",
    "SHP: 0",
    "HWY: 0",
    "BCH: 0",
    "Total score: 0",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| HSE |     |     |     |        HSE      | 7",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']

def test_view_current_score_hse_2hse_adjacent():
    """
    Test script to test viewing current score when  2 "HSE" is on the board and they are adjacent. (TC-07D)
    """
    set_keyboard_input(["2","a1","2","b1","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["BCH", "HSE"], "2": ["BCH", "HSE"], "3": ["BCH", "HSE"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| HSE |     |     |     |        HSE      | 7",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| HSE | HSE |     |     |        HSE      | 6",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 1 + 1 = 2",
    "FAC: 0",
    "SHP: 0",
    "HWY: 0",
    "BCH: 0",
    "Total score: 2",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| HSE | HSE |     |     |        HSE      | 6",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']

def test_view_current_score_hse_2bch_center():
    """
    Test script to test viewing current score when a single "HSE" and 2 "BCH" is on the board and the "BCH" are adjacent to the "HSE". The "BCH" are not in the Right or Left side of the city (TC-07D)
    """
    set_keyboard_input(["2","b2","1","b3","1","c2","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["BCH", "HSE"], "2": ["BCH", "HSE"], "3": ["BCH", "HSE"], "4": ["BCH", "HSE"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 7",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     | HSE |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 7",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     | HSE |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     | BCH |     |     |        BCH      | 7",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 4",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 7",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     | HSE | BCH |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     | BCH |     |     |        BCH      | 6",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 4 = 4",
    "FAC: 0",
    "SHP: 0",
    "HWY: 0",
    "BCH: 1 + 1 = 2",
    "Total score: 6",
    "",
    "Turn 4",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 7",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     | HSE | BCH |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     | BCH |     |     |        BCH      | 6",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']

def test_view_current_score_hse_2shp_adjacent_to_hse_but_not_to_each_other():
    """
    Test script to test viewing current score when a single "HSE" and 2 "SHP" is on the board and the "SHP" are adjacent to the "HSE" but not adjacent to each other. (TC-07D)
    """
    set_keyboard_input(["2","b2","1","a2","1","c2","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["BCH", "HSE"], "2": ["SHP", "HWY"], "3": ["SHP", "HWY"], "4": ["SHP", "HWY"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 7",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     | HSE |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 7",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| SHP | HSE |     |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 4",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 7",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| SHP | HSE | SHP |     |        SHP      | 6",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 2 = 2",
    "FAC: 0",
    "SHP: 1 + 1 = 2",
    "HWY: 0",
    "BCH: 0",
    "Total score: 4",
    "",
    "Turn 4",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 7",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| SHP | HSE | SHP |     |        SHP      | 6",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']

def test_view_current_score_hse_1fac_adjacent():
    """
    Test script to test viewing current score when a single "HSE" and a single "FAC" is on the board and they are adjacent. (TC-07D)
    """
    set_keyboard_input(["2","b2","1","a2","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["BCH", "HSE"], "2": ["FAC", "HWY"], "3": ["FAC", "HWY"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 7",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     | HSE |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 7",
    "  +-----+-----+-----+-----+        FAC      | 7",
    " 2| FAC | HSE |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 1 = 1",
    "FAC: 1 = 1",
    "SHP: 0",
    "HWY: 0",
    "BCH: 0",
    "Total score: 2",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 7",
    "  +-----+-----+-----+-----+        FAC      | 7",
    " 2| FAC | HSE |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']

def test_view_current_score_shp_single_shp():
    """
    Test script to test viewing current score when a single "SHP" is on the board. (TC-07E)
    """
    set_keyboard_input(["1","b2","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["SHP", "HWY"], "2": ["SHP", "HWY"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     | SHP |     |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 0",
    "FAC: 0",
    "SHP: 0",
    "HWY: 0",
    "BCH: 0",
    "Total score: 0",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     | SHP |     |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']

def test_view_current_score_shp_single_bch_adjacent_not_in_center():
    """
    Test script to test viewing current score when a single "SHP" and a single "BCH" is on the board and they are adjacent. The "BCH" is on the right or left side of the City. (TC-07E)
    """
    set_keyboard_input(["1","b2","1","a2","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["SHP", "HWY"], "2": ["BCH", "HSE"], "3": ["BCH", "HSE"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     | SHP |     |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| BCH | SHP |     |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 7",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 0",
    "FAC: 0",
    "SHP: 1 = 1",
    "HWY: 0",
    "BCH: 3 = 3",
    "Total score: 4",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| BCH | SHP |     |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 7",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']
    

def test_view_current_score_shp_single_bch_adjacent_single_fac_adjacent_bch_not_in_center():
    """
    Test script to test viewing current score when a single "SHP", single "BCH" and a single "FAC" is on the board. They are adjacent to the SHP.  The "BCH" is on the Right or Left side of the City. (TC-07E)
    """
    set_keyboard_input(["1","b2","1","a2","1","c2","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["SHP", "HWY"], "2": ["BCH", "HSE"], "3": ["FAC", "HWY"], "4": ["FAC", "HWY"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     | SHP |     |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| BCH | SHP |     |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 7",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 4",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 7",
    " 2| BCH | SHP | FAC |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 7",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 0",
    "FAC: 1 = 1",
    "SHP: 2 = 2",
    "HWY: 0",
    "BCH: 3 = 3",
    "Total score: 6",
    "",
    "Turn 4",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 7",
    " 2| BCH | SHP | FAC |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 7",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']


def test_view_current_score_shp_2_bch_adjacent_single_fac_adjacent_bch_not_in_center():
    """
    Test script to test viewing current score when a single "SHP", 2 "BCH" and a single "FAC" is on the board. They are adjacent.  The "BCH" is on the Right or Left side of the City. (TC-07E)
    """
    set_keyboard_input(["1","a2","1","a1","1","a3","1","b2","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["SHP", "HWY"], "2": ["BCH", "HSE"], "3": ["BCH", "HSE"], "4": ["FAC", "HWY"], "5": ["FAC", "HWY"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| SHP |     |     |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| BCH |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| SHP |     |     |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 7",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 4",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| BCH |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| SHP |     |     |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3| BCH |     |     |     |        BCH      | 6",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 5",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| BCH |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 7",
    " 2| SHP | FAC |     |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3| BCH |     |     |     |        BCH      | 6",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 0",
    "FAC: 1 = 1",
    "SHP: 2 = 2",
    "HWY: 0",
    "BCH: 3 + 3 = 6",
    "Total score: 9",
    "",
    "Turn 5",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| BCH |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 7",
    " 2| SHP | FAC |     |     |        SHP      | 7",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3| BCH |     |     |     |        BCH      | 6",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a FAC',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']
    
def test_view_current_score_hwy_single_hwy():
    """
    Test script to test viewing current score when a single "HWY" is on the board (TC-07F)
    """
    set_keyboard_input(["2","a2","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["SHP", "HWY"], "2": ["BCH", "HSE"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| HWY |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 7",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 0",
    "FAC: 0",
    "SHP: 0",
    "HWY: 1 = 1",
    "BCH: 0",
    "Total score: 1",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| HWY |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 7",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a BCH',
    '2. Build a HSE', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']

def test_view_current_score_hwy_2_hwy_adjacent_on_single_row():
    """
    Test script to test viewing current score when a 2 "HWY" is on the board all adjacent on the same row. (TC-07F)
    """
    set_keyboard_input(["2","a2","2","b2","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["SHP", "HWY"], "2": ["SHP", "HWY"], "3": ["SHP", "HWY"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| HWY |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 7",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| HWY | HWY |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 6",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 0",
    "FAC: 0",
    "SHP: 0",
    "HWY: 2 + 2 = 4",
    "BCH: 0",
    "Total score: 4",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| HWY | HWY |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 6",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']


def test_view_current_score_hwy_4_hwy_adjacent_on_single_row():
    """
    Test script to test viewing current score when a 4 "HWY" is on the board all adjacent on the same row. (TC-07F)
    """
    set_keyboard_input(["2","a2","2","b2","2","c2","2","d2","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["SHP", "HWY"], "2": ["SHP", "HWY"], "3": ["SHP", "HWY"], "4": ["SHP", "HWY"], "5": ["SHP", "HWY"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| HWY |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 7",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| HWY | HWY |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 6",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 4",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| HWY | HWY | HWY |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 5",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 5",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| HWY | HWY | HWY | HWY |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 4",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 0",
    "FAC: 0",
    "SHP: 0",
    "HWY: 4 + 4 + 4 + 4 = 16",
    "BCH: 0",
    "Total score: 16",
    "",
    "Turn 5",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| HWY | HWY | HWY | HWY |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 4",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']

def test_view_currentscore_hwy_2_hwy_adjacent_on_single_row_1hwy_adjacent_on_different_row():
    """
    Test script to test viewing current score when a 2 "HWY" is on the board all adjacent on the same row. (TC-07F)
    """
    set_keyboard_input(["2","a2","2","b2","2","a1","4","0"])

    test_game = Game()
    test_game.randomized_building_history = {"1": ["SHP", "HWY"], "2": ["SHP", "HWY"], "3": ["SHP", "HWY"], "4": ["SHP", "HWY"]}
    test_game.building_pool = defaultBuildingPool
    test_game.start_new_turn()
    result = get_display_output()

    assert result == ["", "Turn 1",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2|     |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 8",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 2",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| HWY |     |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 7",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 3",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1|     |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| HWY | HWY |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 6",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "Build where? ",
    "",
    "Turn 4",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| HWY |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| HWY | HWY |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 5",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ',
    "",
    "HSE: 0",
    "FAC: 0",
    "SHP: 0",
    "HWY: 1 + 2 + 2 = 5",
    "BCH: 0",
    "Total score: 5",
    "",
    "Turn 4",
    "     A     B     C     D           Building   Remaining",
    "  +-----+-----+-----+-----+        --------------------",
    " 1| HWY |     |     |     |        HSE      | 8",
    "  +-----+-----+-----+-----+        FAC      | 8",
    " 2| HWY | HWY |     |     |        SHP      | 8",
    "  +-----+-----+-----+-----+        HWY      | 5",
    " 3|     |     |     |     |        BCH      | 8",
    "  +-----+-----+-----+-----+",
    " 4|     |     |     |     |",
    "  +-----+-----+-----+-----+",
    '1. Build a SHP',
    '2. Build a HWY', 
    '3. See remaining buildings',
    '4. See current score',
    '', 
    '5. Save game', 
    '0. Exit to main menu', 
    'Your choice? ']


@pytest.mark.parametrize("input, turnNumber, buildingBoard, currentScore, actualBoard, buildingPool",
[(["4", "0"], 2, gameBoard1PRK, score1PRK, actualBoard1PRK, newBuildingPool1PRK), (["4", "0"], 3, gameBoard2PRK, score2PRK, actualBoard2PRK, newBuildingPool2PRK), 
(["4", "0"], 4, gameBoard3PRK, score3PRK, actualBoard3PRK, newBuildingPool3PRK), (["4", "0"], 5, gameBoard4PRK, score4PRK, actualBoard4PRK,newBuildingPool4PRK),
(["4", "0"], 6, gameBoard5PRK, score5PRK, actualBoard5PRK, newBuildingPool5PRK), (["4", "0"], 7, gameBoard6PRK, score6PRK, actualBoard6PRK, newBuildingPool6PRK), 
(["4", "0"], 8, gameBoard7PRK, score7PRK, actualBoard7PRK, newBuildingPool7PRK), (["4", "0"], 9, gameBoard8PRK, score8PRK, actualBoard8PRK, newBuildingPool8PRK)])
def test_view_current_score_prk(input,turnNumber,buildingBoard,currentScore,actualBoard, buildingPool):
    """
    Test script to test score for "PRK" (Park)
    """
    set_keyboard_input(input)

    test_game = Game()
    test_game.randomized_building_history = {"1": ["HSE", "MON"], "2": ["HSE", "MON"], "3": ["HSE", "MON"], "4": ["HSE", "MON"], "5": ["HSE", "MON"],
    "6": ["HSE", "MON"], "7": ["HSE", "MON"], "8": ["HSE", "MON"],"9": ["HSE", "MON"]}
    test_game.building_pool = buildingPool
    test_game.board = actualBoard
    test_game.turn_num = turnNumber
    test_game.start_new_turn()
    result = get_display_output()

    turnNumberArray = ["Turn " + str(turnNumber)]

    assert result == [""] + turnNumberArray + buildingBoard + gameMenu + [""] + currentScore + [""] + turnNumberArray + buildingBoard + gameMenu

@pytest.mark.parametrize("input, turnNumber, buildingBoard, currentScore, actualBoard, buildingPool",
[(["4", "0"], 2, gameBoard1MONCornerSquare, score1MONCorner, actualBoard1MONCorner, newBuildingPool1MON), 
(["4", "0"], 2, gameBoard1MONNotCornerSquare, score1MONNotCorner, actualBoard1MONNotCorner, newBuildingPool1MON), 
(["4", "0"], 4, gameBoard3MONCorner1MONNotCorner, score3MONCorner, actualBoard3MONCorner1NotCorner, newBuildingPool4MON), 
(["4", "0"], 5, gameBoard4MONCorner, score3MONCorner, actualBoard4MONCorner, newBuildingPool4MON)])
def test_view_current_score_mon(input,turnNumber,buildingBoard,currentScore,actualBoard, buildingPool):
    """
    Test script to test score for "MON" (Monument)
    """
    set_keyboard_input(input)

    test_game = Game()
    test_game.randomized_building_history = {"1": ["HSE", "MON"], "2": ["HSE", "MON"], "3": ["HSE", "MON"], "4": ["HSE", "MON"], "5": ["HSE", "MON"],
    "6": ["HSE", "MON"], "7": ["HSE", "MON"], "8": ["HSE", "MON"],"9": ["HSE", "MON"]}
    test_game.building_pool = buildingPool
    test_game.board = actualBoard
    test_game.turn_num = turnNumber
    test_game.start_new_turn()
    result = get_display_output()

    turnNumberArray = ["Turn " + str(turnNumber)]

    assert result == [""] + turnNumberArray + buildingBoard + gameMenu + [""] + currentScore + [""] + turnNumberArray + buildingBoard + gameMenu